credentials: &default_creds
  username: "user"
  password: "password"

anonymizer:
  host: "rabbitmq"
  localhost: "localhost"
  port: "5672"
  <<: *default_creds
  queue_name: "anonymizer"
  send_queue: "xnat"

radiomics:
  host: "rabbitmq"
  localhost: "localhost"
  port: "5672"
  <<: *default_creds
  queue_name: "radiomics"
  send_queue: "xnat"
  
xnat:
  host: "rabbitmq"
  localhost: "localhost"
  port: "5672"
  <<: *default_creds
  queue_name: "xnat"
  send_queue: 

xnat_listener:
  host: "rabbitmq"
  localhost: "localhost"
  port: "5672"
  <<: *default_creds
  send_queue: "radiomics"

postgres:
  host: "host.docker.internal"
  port: "5432"
  username: "postgres"
  password: "postgres"
  db: "postgres"

rabbitMQ:
  host: "host.docker.internal"
  port: "5672"
  <<: *default_creds
  queue_name: "DICOM_Processor"
