anonymizer:
  host: "rabbitmq"
  localhost: "localhost"
  port: "5672"
  username: "guest"
  password: "guest"
  queue_name: "anonymizer"
  send_queue: "xnat"

radiomics:
  host: "rabbitmq"
  localhost: "localhost"
  port: "5672"
  username: "guest"
  password: "guest"
  queue_name: "radiomics"
  send_queue: "xnat"
  
xnat:
  host: "rabbitmq"
  localhost: "localhost"
  port: "5672"
  username: "guest"
  password: "guest"
  queue_name: "xnat"
  send_queue: 

xnat_listener:
  host: "rabbitmq"
  localhost: "localhost"
  port: "5672"
  username: "guest"
  password: "guest"
  send_queue: "radiomics"